# How to use schemas:
#
# from cerberus import Validator
#
# v = Validator(POST_SCHEMA, allow_unknown=True)
# is_valid = v.validate(post)  # returns True or False
# validated_data = v.document  # returns validated document or None if post is not valid
# validated_data = v.validated(post)  # validates and returns validated data or None if post is not valid
# errors = v.errors  # an array of errors, if occurred


POST_SCHEMA = {
    'identifier': {'type': 'string', 'empty': False},
    'permlink': {'type': 'string', 'empty': False},
    'max_cashout_time': {'type': 'datetime'},
    'cashout_time': {'type': 'datetime'},
    'percent_steem_dollars': {'type': 'number', 'coerce': int},
    'title': {'type': 'string', 'empty': False},
    'tags': {'type': 'list',
             'empty': True,
             'schema': {'type': 'string'}},
    'curator_payout_value': {'type': 'dict',
                             'schema': {'asset': {'type': 'string'},
                                        'amount': {'type': 'number'}}},
    'net_rshares': {'type': 'number', 'coerce': float},
    'parent_permlink': {'type': 'string', 'empty': False},
    'reblogged_by': {'type': 'list',
                     'empty': True,
                     'schema': {'type': 'string'}},
    'body': {'type': 'string', 'empty': False},
    'vote_rshares': {'type': 'number', 'coerce': float},
    'author_rewards': {'type': 'number', 'coerce': int},
    'promoted': {'type': 'dict',
                 'schema': {'asset': {'type': 'string'},
                            'amount': {'type': 'number'}}},
    'author_reputation': {'type': 'number', 'coerce': float},
    'parent_author': {'type': 'string', 'empty': True},
    'category': {'type': 'string', 'empty': False},
    'last_payout': {'type': 'datetime'},
    'net_votes': {'type': 'number', 'coerce': int},
    'total_vote_weight': {'type': 'number', 'coerce': float},
    'children': {'type': 'number', 'coerce': int},
    'beneficiaries': {'type': 'list',
                      'empty': True,
                      'schema': {'type': 'dict',
                                 'schema': {'weight': {'type': 'number', 'coerce': int},
                                            'account': {'type': 'string'}}}},
    'reward_weight': {'type': 'number', 'coerce': int},
    'author': {'type': 'string', 'empty': False},
    'community': {'type': 'string', 'empty': True},
    'body_length': {'type': 'number', 'coerce': int},
    'children_abs_rshares': {'type': 'number', 'coerce': float},
    'sum_payout_data': {'type': 'dict',
                        'schema': {'asset': {'type': 'string'},
                                   'amount': {'type': 'number'}}},
    'total_pending_payout_value': {'type': 'dict',
                                   'schema': {'asset': {'type': 'string'},
                                              'amount': {'type': 'number'}}},
    'score_trending': {'type': 'number'},
    'score_hot': {'type': 'number'},
    'depth': {'type': 'number', 'coerce': int},
    'id': {'type': 'number', 'coerce': int},
    'replies': {'type': 'list', 'empty': True},
    'root_comment': {'type': 'number', 'coerce': int},
    'root_title': {'type': 'string', 'empty': False},
    'url': {'type': 'string', 'empty': False},
    'created': {'type': 'datetime'},
    'pending_payout_value': {'type': 'dict',
                             'schema': {'asset': {'type': 'string'},
                                        'amount': {'type': 'number'}}},
    'total_payout_value': {'type': 'dict',
                           'schema': {'asset': {'type': 'string'},
                                      'amount': {'type': 'number'}}},
    'active_votes': {'type': 'list',
                     'empty': True,
                     'schema': {'type': 'dict',
                                'schema': {'reputation': {'type': 'number', 'coerce': float},
                                           'percent': {'type': 'number', 'coerce': int},
                                           'voter': {'type': 'string'},
                                           'weight': {'type': 'number', 'coerce': int},
                                           'time': {'type': 'string'},
                                           'rshares': {'type': 'number', 'coerce': float}}}},
    'last_update': {'type': 'datetime'},
    'json_metadata': {'type': 'dict',
                      'allow_unknown': True,
                      'schema': {'tags': {'type': 'list',
                                          'empty': False,
                                          'schema': {'type': 'string'}},
                                 'app': {'type': 'string'}}},
    'active': {'type': 'datetime'},
    'max_accepted_payout': {'type': 'dict',
                            'schema': {'asset': {'type': 'string'},
                                       'amount': {'type': 'number'}}},
    'abs_rshares': {'type': 'number', 'coerce': float},
    'allow_votes': {'type': 'boolean'},
    'allow_curation_rewards': {'type': 'boolean'},
    'allow_replies': {'type': 'boolean'}
}
